name: test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  FOUNDRY_PROFILE: ci

jobs:
  check:
    strategy:
      fail-fast: true

    name: Foundry project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly
      - name: Install Dependencies
        run: npm install

      - name: Run Forge tests
        run: |
          forge test -vvv --no-match-path ./test/mainnetFork/tests.t.sol
        id: test

      - name: deploy
        env:
          DEPLOYER_PRIVATE_KEY: 1d6dd2d1632dc861c697982d99cde7475a96f4b7ff9ab4352096be3700f8c4af
          TEST_PRIVATE_KEY: 1d6dd2d1632dc861c697982d99cde7475a96f4b7ff9ab4352096be3700f8c4af
        run: |
          npx hardhat deploy --tags pass,main,setup --network hardhat

